### ISSUE TITLE
Tachiyomi Recognition

### ISSUE THREAD

**Issue by torebake** [KotatsuApp/Kotatsu#684] opened 2024-01-17 21:03 UTC
### Describe your suggested feature

I have no idea how to do it, but it would be really, really cool if Kotatsu could recognize Tachiyomi backups. I had to move off of Tachiyomi due to them stopping official support, and migrating my entire library (1500+ entries) is going to be a hassle to say the least. I'm sure I'm not the only one with this problem. 

Although, if it doesn't work, no problem.

Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment] 2024-01-17 21:29
Duplicate of #301

**Closed** 2024-01-17 21:29 UTC
Labels: feature request
