### ISSUE TITLE
Edge taps in RTL not reversed

### ISSUE THREAD

**Issue by AdriaanFriesen** [KotatsuApp/Kotatsu#214] opened 2022-08-13 20:27 UTC
### Brief summary

Edge taps are not reversed in RTL mode, ie. tapping on the right edge moves forward a page, tapping on the left moves backward.

### Steps to reproduce

1. Open a manga
2. Turn on RTL reading mode
3. Tap on right edge
4. Manga moves forward one page instead of backward

### Kotatsu version

3.4.8

### Android version

9

### Device

LM-V405QA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment] 2022-08-14 04:26
TL;DR: this is not a bug, that's how it was intended

Tapping on right is more ergonomically then tapping on left edge of phone's screen and "Next page" is also the most frequently action in reader, so tapping on the right edge is always a "Next page", not a "Right-hand page". I agree this is not really intuitive way, so maybe we should make an option for it?

**Comment by AdriaanFriesen** [comment] 2022-08-14 05:14
Yeah, that would be best.

**Comment by ztimms73** [comment] 2022-08-27 10:43
Fixed in [3.4.12](https://github.com/KotatsuApp/Kotatsu/releases/tag/v3.4.12)

**Closed by ztimms73** 2022-08-27 10:43 UTC
Labels: bug
