### ISSUE TITLE
Can't choose external storage(SD card) as Folder for Downloads

### ISSUE THREAD

**Issue by Hell0Earth** [KotatsuApp/Kotatsu#580] opened 2023-11-30 04:45 UTC
### Brief summary

I have this directory to save kotatsu backups: /storage/1DE1-5CEA/MyThingsByPinkDiamond/Manga/Kotatsu/Backup and  works ok but when I try to select" /storage/1DE1-5CEA/MyThingsByPinkDiamond/Manga/Kotatsu/ as Folder to save downloads, I get an error.

![Screenshot_2023-11-30-01-41-51-366_org koitharu kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/93066706/42618826-06d1-46e1-93de-d2c0fc86fada)

![Screenshot_2023-11-30-01-33-40-673_org koitharu kotatsu](https://github.com/KotatsuApp/Kotatsu/assets/93066706/b451cb02-268b-4552-af3b-eb28f4b7facd)

### Steps to reproduce

1)Go to Settings/Downloads/Folder for Downloads/Pick custom directory.
2) Try to select a folder on SD card.
3) Get error.

### Kotatsu version

6.4.2

### Android version

Miui 12.5.3 based on Android 10

### Device

Redmi Note 5 pro (whyred)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If this is an issue with a parser, I should be opening an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment] 2023-12-01 07:41
Looks like duplicate of #570 , this is an Android 10 specified issue, will try to fix it soon

**Comment by UniverseCodex01** [comment] 2024-01-31 22:54
> Looks like duplicate of #570 , this is an Android 10 specified issue, will try to fix it soon

Now I can add custom internal storage directory to local storage srouces but SD directories still with access error but backups can be saved to a custom SD card directory.

**Comment by Hell0Earth** [comment] 2024-04-24 11:10
Impossible to add custom local directories form SD card: "You have no access to this file or directorie" same issue for downloads, except for backups.

**Closed** 2024-08-10 23:11 UTC
Labels: bug
