### ISSUE TITLE
Update notice

### ISSUE THREAD

**Issue by MaiVenn** [KotatsuApp/Kotatsu#1035] opened 2024-08-14 01:10 UTC
### Brief summary

Update notice keeps popping up even after multiple update

### Steps to reproduce

https://github.com/user-attachments/assets/a40bcc15-4191-46a1-a54f-a759c234bac2

### Kotatsu version

7.4.2

### Android version

13

### Device

ITEL A665L

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by MariusAlbrecht** [comment] 2024-08-14 11:44
this is a duplicate.

**Comment by ztimms73** [comment] 2024-08-14 13:29
Duplicate of #1032

**Closed** 2024-08-14 13:29 UTC
Labels: bug
