### ISSUE TITLE
Thumbnail changing option

### ISSUE THREAD

**Issue by Mhuzaifakhalid** [KotatsuApp/Kotatsu#1000] opened 2024-07-30 10:46 UTC
### Describe your suggested feature

The app should have an option to change the thumbnails of the titles that we have in the favourites. It should give us an option to select a picture from our gallery. Or even better, be able to browse through a specific source and selecting a title to extract its thumbnail (its nothing important but it would be cool)  

This is needed as some titles in some sources don't have a proper thumbnail, mostly just a random screen shot of a page  (check the titles lookism and tower of god in manganato.to for example) 

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ztimms73** [comment] 2024-07-31 15:42
Sorry, creator of the 1000th ticket, but this is a duplicate of #418

**Closed** 2024-07-31 15:43 UTC
Labels: feature request
