### ISSUE TITLE
Feature to migrate from Tachiyomi.

### ISSUE THREAD

**Issue by UniverseCodex01** [KotatsuApp/Kotatsu#455] opened 2023-08-14 12:50 UTC
### Describe your suggested feature

With the last pre released version I take the decision of fully migrate from Tachiyomi to Kotatsu, the problem, I have a lot of favourites and library custom categories. I want to suggest that add a migrate option to recover Tachiyomi library on Kotatsu will be a good feature. If library categories can't be recover but favourites can be recovered, it's fine.

Thanks for your work with Kotatsu, it's an amazing reader app. I can understand if this feature it's not planned or can't be added.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by davvarrr** [comment] 2023-08-14 13:14
Duplicate of https://github.com/KotatsuApp/Kotatsu/issues/301

**Closed** 2023-08-14 14:16 UTC
Labels: feature request
