### ISSUE TITLE
Request about downloading 

### ISSUE THREAD

**Issue by Milenavcb** [KotatsuApp/Kotatsu#797] opened 2024-02-27 21:00 UTC
### Describe your suggested feature

I think that an activation option so that after reading a downloaded chapter it will self-delete would be very interesting. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment] 2024-02-27 22:29
Duplicate of #603

**Closed** 2024-02-27 22:29 UTC
Labels: feature request
