### ISSUE TITLE
7.7 Crashing

### ISSUE THREAD

**Issue by agent2111** [KotatsuApp/Kotatsu#1194] opened 2024-11-30 17:02 UTC
### Brief summary

The app crashes every time within 5 seconds of the app opening but the crashes sometimes takes it back to the home page of the app before eventually crashing.

### Kotatsu version

7.7

### Android version

9

### Device

Samsung Galaxy S8

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Ero-gamer** [comment] 2024-12-01 19:07
Exactly, same as beta version, crash issue is not fixed yet on the latest "stable" version.

**Comment by dragonx943** [comment] 2024-12-02 06:10
> ### Brief summary
> The app crashes every time within 5 seconds of the app opening but the crashes sometimes takes it back to the home page of the app before eventually crashing.
> 
> ### Steps to reproduce
> _No response_
> 
> ### Kotatsu version
> 7.7
> 
> ### Android version
> 9
> 
> ### Device
> Samsung Galaxy S8
> 
> ### Acknowledgements
> * [x]  This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
> * [x]  This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

u can try nightly build :p

**Comment by Koitharu** [comment] 2024-12-03 12:20
It would be nice if someone share crash stacktrace because I cannot reproduce it

**Comment by Koitharu** [comment] 2024-12-03 12:21
And looks like duplicate of #1178 so I close it

**Closed by Koitharu** 2024-12-03 12:21 UTC
Labels: bug

**Comment by Ero-gamer** [comment] 2024-12-04 04:25
> It would be nice if someone share crash stacktrace because I cannot reproduce it

App crash without generating crash log.
