### ISSUE TITLE
migrate manga

### ISSUE THREAD

**Issue by MRhawk480** [KotatsuApp/Kotatsu#681] opened 2024-01-17 16:53 UTC
### Describe your suggested feature

a way to migrate a manga that is in the favorites tab to another like it, this would make it easier when an extension changes its URL, then just use the migrate option

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment] 2024-01-17 17:10
Duplicate of #660

**Closed as not planned** 2024-01-17 17:10 UTC
Labels: feature request
