### ISSUE TITLE
Transfer from tachiyomi

### ISSUE THREAD

**Issue by Rshxh** [KotatsuApp/Kotatsu#408] opened 2023-07-05 01:28 UTC
### Describe your suggested feature

This app is amazing and much lighter compared to tachiyomi, I would've already switched to it if it weren't for hundreds of manga I have tracked in tachiyomi.
Developers of kotatsu, I'd like to request a feature to import the tachiyomi's backup file in kotatsu app, it *probably* wouldn't be hard to do this but idk, if the extensions are missing I was thinking that the user can be promoted to transfer the mangas to another source or skip them. Thanks for reading.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment] 2023-07-05 04:11
Duplicate of #301

**Closed** 2023-07-05 04:11 UTC
Labels: feature request

**Comment by mariodac** [comment] 2024-01-13 20:53
we need this, now that tachiyomi has ended how are we going to migrate to kotatsu?
