### ISSUE TITLE
Change progress percentage to unread count

### ISSUE THREAD

**Issue by arfannn88** [KotatsuApp/Kotatsu#696] opened 2024-01-21 13:15 UTC
### Describe your suggested feature

Change progress percentage to unread count currently we cannot see how much more of the chapter is left after we started reading. It's only showing percentage and that is not helpful at all. I think you should replace that with unread count like tachiyomi app. It will be very beneficial to know how many new chapters came and how many chapter are left to read.

![Screenshot_20240121-190933](https://github.com/KotatsuApp/Kotatsu/assets/124960383/f55bc917-5340-4c57-b5ef-5ccbc979983d)

As you can see I am already done a lot of chapter but the percentage is showing 1% it is not helpful when we are seeing this in favourite library. So replace this with unread.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by rishi2062** [comment] 2024-01-22 10:41
Can i take this up?

**Comment by Koitharu** [comment] 2024-01-22 11:04
First things first we want to add information about chapters count in database, I`ll add it soon and than such features becomes possible to implement

**Comment by Koitharu** [comment] 2024-01-22 11:09
Duplicate of #693 ?

**Closed** 2024-01-22 11:09 UTC
Labels: feature request

**Comment by rishi2062** [comment] 2024-01-22 11:13
In the screenshot, shared above i can see there is current data records of how many they have read out of total chapters, using these data, we can directly replace percentage.
