### ISSUE TITLE
Please add support for Tachiyomi backup

### ISSUE THREAD

**Issue by nvanadsn** [KotatsuApp/Kotatsu#511] opened 2023-10-01 11:03 UTC
### Describe your suggested feature

I want to transfer my readings to the Kotatsu app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment] 2023-10-01 12:11
Duplicate of #301

**Closed** 2023-10-01 12:11 UTC
Labels: feature request
