### ISSUE TITLE
Editable image cover

### ISSUE THREAD

**Issue by harakun24** [KotatsuApp/Kotatsu#712] opened 2024-01-25 06:08 UTC
### Describe your suggested feature

It is nice to have the ability to change image cover of some manga. Thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by harakun24** [comment] 2024-01-26 19:58
Someone please read this

**Comment by ztimms73** [comment] 2024-01-26 20:04
you're right, duplicate of #418

**Closed** 2024-01-26 20:04 UTC
Labels: feature request
