### ISSUE TITLE
Update loop 

### ISSUE THREAD

**Issue by abdullahejazjanjua** [KotatsuApp/Kotatsu#1042] opened 2024-08-15 10:33 UTC
### Brief summary

When I update the app to the latest release version, the app updates and everything but the the update icon stays and I can repeatedly update.

### Steps to reproduce

Press the update icon on the app on the search bar
Click update

### Kotatsu version

7.4.2

### Android version

13

### Device

Samsung galaxy A32

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by User-425** [comment] 2024-08-15 13:54
Same here, using Techno Spark Go 2023

**Comment by wolfkin** [comment] 2024-08-15 19:09
I *just* completed the update to 7.4.2 and I have this bug. It's only been about 15m so I'm not sure if it'll go away by itself but since there is an issue i'll chime in my +1 as well. 

G1 Tab Mini
Android 14
UMIDIGI_G1_Tab_Mini_V1.0_20240522

**Comment by ztimms73** [comment] 2024-08-15 21:48
Duplicate of #1032

**Closed** 2024-08-15 21:48 UTC
Labels: bug
