### ISSUE TITLE
Mark chapter as seen

### ISSUE THREAD

**Issue by Com3Carne** [KotatsuApp/Kotatsu#233] opened 2022-09-23 00:19 UTC
I usually read manga in my smartphone browser. I migrated to your app because I found it interesting. But when I started reading them for him, I couldn't mark the ones I'd already seen. There are some that have more than 1000. It would be nice to have one that has this option.

**Comment by ztimms73** [comment] 2022-09-23 09:38
Duplicate of #56

**Closed by ztimms73** 2022-09-23 09:38 UTC
Labels: feature request
