### ISSUE TITLE
Editable image cover

### ISSUE THREAD

**Issue by harakun24** [KotatsuApp/Kotatsu#710] opened 2024-01-24 17:57 UTC
### Describe your suggested feature

It is nice if we could change the image cover of manga since sometime kotatsu failed to load it. End up with a blank image cover for some manga. Please make it. Thank you. 

This is an example of how kotatsu failed to load an image cover: 
![Screenshot_20240125-002902](https://github.com/KotatsuApp/Kotatsu/assets/50375988/4cc32096-949a-4f58-aac7-e7b4a80f0d16)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment] 2024-01-24 18:45
Duplicate of #418

**Closed** 2024-01-24 18:46 UTC
Labels: feature request
