### ISSUE TITLE
Downloading anything fails

### ISSUE THREAD

**Issue by ShaquibHere** [KotatsuApp/Kotatsu#1083] opened 2024-09-04 15:07 UTC
### Brief summary

Downloading anything manhwa/manhua/manga, it ends up with an error stating channel is closed. I've tried several sources and none of them worked. It was working fine on v7.4.3 but it ends up with error on V7.5. Attaching a screenshot where the error is being shown
![Screenshot_2024-09-04-20-35-13-694_org koitharu kotatsu](https://github.com/user-attachments/assets/296e6178-afed-4b39-b910-dfc746ef5866)

### Steps to reproduce

1. Open any manhwa etc
2. Try downloading the entirety of the series (80-100 chapter or above) will end up with this error.

### Kotatsu version

7.5

### Android version

14.0

### Device

Mi 11 Lite 5G NE

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by Koitharu** [comment] 2024-09-05 06:19
Duplicate of #1072

**Closed by Koitharu** 2024-09-05 06:19 UTC
Labels: bug
