### ISSUE TITLE
Restore option

### ISSUE THREAD

**Issue by GladRedFox719** [KotatsuApp/Kotatsu#998] opened 2024-07-30 10:13 UTC
### Describe your suggested feature

Add another way to restore from backup like supporting Mihon "formerly known as Tachiyomi" backup file extension ".tachibk" it will help other's move from Mihon to Kotatsu.

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.

**Comment by ztimms73** [comment] 2024-07-31 15:46
Duplicate of #301

**Closed** 2024-07-31 15:46 UTC
Labels: feature request
