### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xeno-yuma** [KotatsuApp/Kotatsu#1087] opened 2024-09-06 01:26 UTC
### Brief summary

The update is good and stable to a certain extent because it always closes after a while like version v7.5

### Steps to reproduce

![Screenshot_20240905-192421](https://github.com/user-attachments/assets/2971741f-0fd3-413b-aef3-0e8c48e92002)

### Kotatsu version

v7.5.1

### Android version

6

### Device

Eexperia

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment] 2024-09-06 05:09
Duplicate of #1078

**Closed** 2024-09-06 05:09 UTC
Labels: bug
