### ISSUE TITLE
Animated pages not working

### ISSUE THREAD

**Issue by Z3548x** [KotatsuApp/Kotatsu#1100] opened 2024-09-17 03:24 UTC
### Brief summary

Whenever theres an animated page it just wont work/wont move. 

### Steps to reproduce

1. Go to a site that has an animated tag. 
2. Tap on any manga
3. Find the animated page (usually hard to find since it blends with the other non animated pages) 

### Kotatsu version

7.5.2

### Android version

14

### Device

Infinix gt20 pro

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by ztimms73** [comment] 2024-09-18 04:30
Duplicate of #430

**Closed** 2024-09-18 04:30 UTC
Labels: bug
