### ISSUE TITLE
image bugs 

### ISSUE THREAD

**Issue by kolinrno** [KotatsuApp/Kotatsu#273] opened 2022-12-13 11:49 UTC
### Brief summary

annoying bug, requiring to return to cover view. otherwise it will continue to load without the image. Loooaadinggg.... (read offline or online it's the same) please fix it quickly

### Steps to reproduce

![Screenshot_2022-12-13-18-33-05-80](https://user-images.githubusercontent.com/120464340/207309921-ccc1f291-2bfa-4e38-b69a-0d74447b4ea5.png)
 1.

2.
![Screenshot_2022-12-13-18-33-35-15](https://user-images.githubusercontent.com/120464340/207310055-65338664-76af-4c33-ad0d-63308c6bbfaa.png)

### Kotatsu version

4.0.6 New version

### Android version

5.0

### Device

oppo a37f

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Koitharu** [comment] 2022-12-14 06:31
Duplicate of #256

**Closed by Koitharu** 2022-12-14 06:31 UTC
Labels: bug
