### ISSUE TITLE
Crop Border 

### ISSUE THREAD

**Issue by itachi-10** [KotatsuApp/Kotatsu#520] opened 2023-10-10 14:18 UTC
### Describe your suggested feature

Can u add the crop border feature as it  will increase readability of text in manga for smartphone display as it will crop the white spaces 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by ztimms73** [comment] 2023-10-10 16:58
Duplicate of #326

**Closed** 2023-10-10 16:58 UTC
Labels: feature request
