### ISSUE TITLE
El icono de actualización sigue 

### ISSUE THREAD

**Issue by Em31-cmd** [KotatsuApp/Kotatsu#1033] opened 2024-08-12 18:54 UTC
### Brief summary

El icono de actualización sigue ahí luego de actualizar la app

### Kotatsu version

7.4.2

### Android version

15

### Device

Oppo a78

### Acknowledgements

- [X] This is not a duplicate of an existing issue. Please look through the list of [open issues](https://github.com/KotatsuApp/Kotatsu/issues) before creating a new one.
- [X] This is not an issue with a specific manga source. Otherwise, you have to open an issue in the [parsers repository](https://github.com/KotatsuApp/kotatsu-parsers/issues/new/choose).

**Comment by MariusAlbrecht** [comment] 2024-08-14 11:46
this is a duplicate.

**Comment by ztimms73** [comment] 2024-08-14 13:29
Duplicate of #1032

**Closed** 2024-08-14 13:29 UTC
Labels: bug
